const constituencyNameData = [
    { english_name: "Valmikinagar", hindi_name: "वाल्मीकि नगर" },
    { english_name: "Ramnagar", hindi_name: "रामनगर" },
    { english_name: "Narkatiaganj", hindi_name: "नरकटियागंज" },
    { english_name: "Bagaha", hindi_name: "बगहा" },
    { english_name: "Lauriya", hindi_name: "लौरिया" },
    { english_name: "Nautan", hindi_name: "नौतन" },
    { english_name: "Chanpatia", hindi_name: "चनपटिया" },
    { english_name: "Bettiah", hindi_name: "बेतिया" },
    { english_name: "Sikta", hindi_name: "सिकटा" },
    { english_name: "Raxaul", hindi_name: "रक्सौल" },
    { english_name: "Sugauli", hindi_name: "सुगौली" },
    { english_name: "Narkatia", hindi_name: "नरकटिया" },
    { english_name: "Harsidhi (S.C)", hindi_name: "हरसिद्धि" },
    { english_name: "Govindganj", hindi_name: "गोविंदगंज" },
    { english_name: "Kesaria", hindi_name: "केसरिया" },
    { english_name: "Kalyanpur", hindi_name: "कल्याणपुर" },
    { english_name: "Pipra", hindi_name: "पिपरा, पूर्वी चंपारण" },
    { english_name: "Madhuban", hindi_name: "मधुबन" },
    { english_name: "Motihari", hindi_name: "मोतिहारी" },
    { english_name: "Chiraiya", hindi_name: "चिरैया" },
    { english_name: "Dhaka", hindi_name: "ढाका" },
    { english_name: "Sheohar", hindi_name: "शिवहर" },
    { english_name: "Riga", hindi_name: "रीगा" },
    { english_name: "Bathnaha", hindi_name: "बथनाहा" },
    { english_name: "Parihar", hindi_name: "परिहार" },
    { english_name: "Sursand", hindi_name: "सुरसंड" },
    { english_name: "Bajpatti", hindi_name: "बाजपट्टी" },
    { english_name: "Sitamarhi", hindi_name: "सीतामढ़ी" },
    { english_name: "Runnisaidpur", hindi_name: "रून्नीसैदपुर" },
    { english_name: "Belsand", hindi_name: "बेलसंड" },
    { english_name: "Harlakhi", hindi_name: "हरलाखी" },
    { english_name: "Benipatti", hindi_name: "बेनीपट्टी" },
    { english_name: "Khajauli", hindi_name: "खजौली" },
    { english_name: "Babubarhi", hindi_name: "बाबूबरही" },
    { english_name: "Bisfi", hindi_name: "बिस्फी" },
    { english_name: "Madhubani", hindi_name: "मधुबनी" },
    { english_name: "Rajnagar", hindi_name: "राजनगर" },
    { english_name: "Jhanjharpur", hindi_name: "झंझारपुर" },
    { english_name: "Phulparas", hindi_name: "फुलपरास" },
    { english_name: "Laukaha", hindi_name: "लौकहा" },
    { english_name: "Nirmali", hindi_name: "निर्मली" },
    { english_name: "Pipra", hindi_name: "पिपरा, सुपौल" },
    { english_name: "Supaul", hindi_name: "सुपौल" },
    { english_name: "Triveniganj", hindi_name: "त्रिवेणीगंज" },
    { english_name: "Chhatapur", hindi_name: "छातापुर" },
    { english_name: "Narpatganj", hindi_name: "नरपतगंज" },
    { english_name: "Raniganj", hindi_name: "रानीगंज, अररिया" },
    { english_name: "Forbesganj", hindi_name: "फोर्बेस्गंज" },
    { english_name: "Araria", hindi_name: "अररिया" },
    { english_name: "Jokihat", hindi_name: "जोकीहाट" },
    { english_name: "Sikti", hindi_name: "सिकटी" },
    { english_name: "Bahadurganj", hindi_name: "बहादुरगंज" },
    { english_name: "Thakurganj", hindi_name: "ठाकुरगंज" },
    { english_name: "Kishanganj", hindi_name: "किशनगंज" },
    { english_name: "Kochadhaman", hindi_name: "कोचाधामन" },
    { english_name: "Amour", hindi_name: "अमौर" },
    { english_name: "Baisi", hindi_name: "बैसी" },
    { english_name: "Kasba", hindi_name: "कसबा, पूर्णिया" },
    { english_name: "Banmankhi", hindi_name: "बनमनखी" },
    { english_name: "Rupauli", hindi_name: "रूपौली" },
    { english_name: "Dhamdaha", hindi_name: "धमदाहा" },
    { english_name: "Purnia", hindi_name: "पूर्णिया" },
    { english_name: "Katihar", hindi_name: "कटिहार" },
    { english_name: "Kadwa", hindi_name: "कदवा" },
    { english_name: "Balrampur", hindi_name: "बलरामपुर" },
    { english_name: "Pranpur", hindi_name: "प्राणपुर" },
    { english_name: "Manihari", hindi_name: "मनिहारी" },
    { english_name: "Barari", hindi_name: "बरारी" },
    { english_name: "Korha", hindi_name: "कोरहा" },
    { english_name: "Alamnagar", hindi_name: "आलमनगर" },
    { english_name: "Bihariganj", hindi_name: "बिहारीगंज" },
    { english_name: "Singheshwar", hindi_name: "सिंहेश्वर" },
    { english_name: "Madhepura", hindi_name: "मधेपुरा" },
    { english_name: "Sonbarsha", hindi_name: "सोनबर्षा,सहरसा" },
    { english_name: "Saharsa", hindi_name: "सहरसा" },
    { english_name: "Simri Bakhtiarpur", hindi_name: "सिमरी बख्तियारपुर" },
    { english_name: "Mahishi", hindi_name: "महिषी" },
    { english_name: "Kusheshwar Asthan", hindi_name: "कुशेश्वरस्थान" },
    { english_name: "Gaura Bauram", hindi_name: "गौरा बौराम" },
    { english_name: "Benipur", hindi_name: "बेनीपुर" },
    { english_name: "Alinagar", hindi_name: "अलीनगर" },
    { english_name: "Darbhanga Rural", hindi_name: "दरभंगा ग्रामीण" },
    { english_name: "Darbhanga", hindi_name: "दरभंगा" },
    { english_name: "Hayaghat", hindi_name: "हायाघाट" },
    { english_name: "Bahadurpur", hindi_name: "बहादुरपुर" },
    { english_name: "Keoti", hindi_name: "केवटी" },
    { english_name: "Jale", hindi_name: "जाले" },
    { english_name: "Gaighat", hindi_name: "गायघाट" },
    { english_name: "Aurai", hindi_name: "औराई" },
    { english_name: "Minapur", hindi_name: "मीनापुर" },
    { english_name: "Bochaha", hindi_name: "बोचहां" },
    { english_name: "Sakra", hindi_name: "सकरा" },
    { english_name: "Kurhani", hindi_name: "कुढ़नी" },
    { english_name: "Muzaffarpur", hindi_name: "मुजफ्फरपुर" },
    { english_name: "Kanti", hindi_name: "कांटी" },
    { english_name: "Baruraj", hindi_name: "बरुराज" },
    { english_name: "Paroo", hindi_name: "पारू" },
    { english_name: "Sahebganj", hindi_name: "साहेबगंज, मुजफ्फरपुर" },
    { english_name: "Baikunthpur", hindi_name: "बैकुंठपुर" },
    { english_name: "Barauli", hindi_name: "बरौली" },
    { english_name: "Gopalganj", hindi_name: "गोपालगंज" },
    { english_name: "Kuchaikote", hindi_name: "कुचायकोटे" },
    { english_name: "Bhorey", hindi_name: "भोरे" },
    { english_name: "Hathua", hindi_name: "हथुआ" },
    { english_name: "Siwan", hindi_name: "सिवान" },
    { english_name: "Ziradei", hindi_name: "जीरादेई" },
    { english_name: "Darauli", hindi_name: "दरौली" },
    { english_name: "Raghunathpur", hindi_name: "रघुनाथपुर, सीवान" },
    { english_name: "Daraundha", hindi_name: "दारौंदा" },
    { english_name: "Barharia", hindi_name: "बड़हरिया" },
    { english_name: "Goriakothi", hindi_name: "गोरियाकोठी" },
    { english_name: "Maharajganj", hindi_name: "महाराजगंज, सीवान" },
    { english_name: "Ekma", hindi_name: "एकमा" },
    { english_name: "Manjhi", hindi_name: "मांझी" },
    { english_name: "Baniapur", hindi_name: "बनियापुर" },
    { english_name: "Taraiya", hindi_name: "तरैया" },
    { english_name: "Marhaura", hindi_name: "मढ़ौरा" },
    { english_name: "Chapra", hindi_name: "छपरा" },
    { english_name: "Garkha", hindi_name: "गरखा" },
    { english_name: "Amnour", hindi_name: "अमनौर" },
    { english_name: "Parsa", hindi_name: "परसा" },
    { english_name: "Sonepur", hindi_name: "सोनपुर" },
    { english_name: "Hajipur", hindi_name: "हाजीपुर" },
    { english_name: "Lalganj", hindi_name: "लालगंज" },
    { english_name: "Vaishali", hindi_name: "वैशाली" },
    { english_name: "Mahua", hindi_name: "महुआ" },
    { english_name: "Rajapakar", hindi_name: "राजा पाकर" },
    { english_name: "Raghopur", hindi_name: "राघोपुर वैशाली" },
    { english_name: "Mahnar", hindi_name: "महनार" },
    { english_name: "Patepur", hindi_name: "पातेपुर" },
    { english_name: "Kalyanpur", hindi_name: "कल्याणपुर, समस्तीपुर" },
    { english_name: "Warisnagar", hindi_name: "वारिसनगर" },
    { english_name: "Samastipur", hindi_name: "समस्तीपुर" },
    { english_name: "Ujiarpur", hindi_name: "उजिआरपुर" },
    { english_name: "Morwa", hindi_name: "मोरवा" },
    { english_name: "Sarairanjan", hindi_name: "सरायरंजन" },
    { english_name: "Mohiuddinnagar", hindi_name: "मोहिउद्दीननगर" },
    { english_name: "Bibhutipur", hindi_name: "बिभूतिपुर" },
    { english_name: "Rosera", hindi_name: "रोसड़ा" },
    { english_name: "Hasanpur", hindi_name: "हसनपुर" },
    { english_name: "Cheria Bariarpur", hindi_name: "चेरिया बरियारपुर" },
    { english_name: "Bachhwara", hindi_name: "बछवाड़ा" },
    { english_name: "Teghra", hindi_name: "तेघरा" },
    { english_name: "Matihani", hindi_name: "मटिहानी" },
    { english_name: "Sahebpur Kamal", hindi_name: "साहेबपुर कमाल" },
    { english_name: "Begusarai", hindi_name: "बेगूसराय" },
    { english_name: "Bakhri", hindi_name: "बखरी" },
    { english_name: "Alauli", hindi_name: "अलौली" },
    { english_name: "Khagaria", hindi_name: "खगड़िया" },
    { english_name: "Beldaur", hindi_name: "बेलदौर" },
    { english_name: "Parbatta", hindi_name: "परबत्ता" },
    { english_name: "Bihpur", hindi_name: "बिहपुर" },
    { english_name: "Gopalpur", hindi_name: "गोपालपुर" },
    { english_name: "Pirpainti", hindi_name: "पिरपैंती" },
    { english_name: "Kahalgaon", hindi_name: "कहलगांव" },
    { english_name: "Bhagalpur", hindi_name: "भागलपुर" },
    { english_name: "Sultanganj", hindi_name: "सुल्तानगंज" },
    { english_name: "Nathnagar", hindi_name: "नाथनगर" },
    { english_name: "Amarpur", hindi_name: "अमरपुर" },
    { english_name: "Dhauraiya", hindi_name: "धोरैया" },
    { english_name: "Banka", hindi_name: "बाँका" },
    { english_name: "Katoria", hindi_name: "कटोरिया" },
    { english_name: "Belhar", hindi_name: "बेलहर" },
    { english_name: "Tarapur", hindi_name: "तारापुर" },
    { english_name: "Munger", hindi_name: "मुंगेर" },
    { english_name: "Jamalpur", hindi_name: "जमालपुर, मुंगेर" },
    { english_name: "Suryagarha", hindi_name: "सूर्यगढ़ा" },
    { english_name: "Lakhisarai", hindi_name: "लखीसराय" },
    { english_name: "Sheikhpura", hindi_name: "शेखपुरा" },
    { english_name: "Barbigha", hindi_name: "बरबीघा" },
    { english_name: "Asthawan", hindi_name: "अस्थावां" },
    { english_name: "Biharsharif", hindi_name: "बिहारशरीफ" },
    { english_name: "Rajgir", hindi_name: "राजगीर" },
    { english_name: "Islampur", hindi_name: "इस्लामपुर, नालन्दा" },
    { english_name: "Hilsa", hindi_name: "हिलसा" },
    { english_name: "Nalanda", hindi_name: "नालन्दा" },
    { english_name: "Harnaut", hindi_name: "हरनौत" },
    { english_name: "Mokama", hindi_name: "मोकामा" },
    { english_name: "Barh", hindi_name: "बाढ़" },
    { english_name: "Bakhtiarpur", hindi_name: "बख्तियारपुर" },
    { english_name: "Digha", hindi_name: "दीघा" },
    { english_name: "Bankipur", hindi_name: "बांकीपुर" },
    { english_name: "Kumhrar", hindi_name: "कुम्हरार" },
    { english_name: "Patna Sahib", hindi_name: "पटना साहिब" },
    { english_name: "Fatuha", hindi_name: "फतुहा" },
    { english_name: "Danapur", hindi_name: "दानापुर" },
    { english_name: "Maner", hindi_name: "मनेर" },
    { english_name: "Phulwari", hindi_name: "फुलवारी" },
    { english_name: "Masaurhi", hindi_name: "मसौढ़ी" },
    { english_name: "Paliganj", hindi_name: "पालीगंज" },
    { english_name: "Bikram", hindi_name: "बिक्रम" },
    { english_name: "Sandesh", hindi_name: "संदेश" },
    { english_name: "Barhara", hindi_name: "बरहरा" },
    { english_name: "Arrah", hindi_name: "आरा" },
    { english_name: "Agiaon", hindi_name: "अगिआंव" },
    { english_name: "Tarari", hindi_name: "तरारी" },
    { english_name: "Jagdishpur", hindi_name: "जगदीशपुर" },
    { english_name: "Shahpur", hindi_name: "शाहपुर" },
    { english_name: "Brahampur", hindi_name: "ब्रह्मपुर" },
    { english_name: "Buxar", hindi_name: "बक्सर" },
    { english_name: "Dumraon", hindi_name: "डुमरांव" },
    { english_name: "Rajpur", hindi_name: "राजपुर" },
    { english_name: "Ramgarh", hindi_name: "रामगढ़, कैमूर" },
    { english_name: "Mohania", hindi_name: "मोहनिया" },
    { english_name: "Bhabua", hindi_name: "भभुआ" },
    { english_name: "Chainpur", hindi_name: "चैनपुर" },
    { english_name: "Chenari", hindi_name: "चेनारी" },
    { english_name: "Sasaram", hindi_name: "सासाराम" },
    { english_name: "Kargahar", hindi_name: "करगहर" },
    { english_name: "Dinara", hindi_name: "दिनारा" },
    { english_name: "Nokha", hindi_name: "नोखा" },
    { english_name: "Dehri", hindi_name: "डेहरी" },
    { english_name: "Karakat", hindi_name: "काराकाट" },
    { english_name: "Arwal", hindi_name: "अरवल" },
    { english_name: "Kurtha", hindi_name: "कुर्था" },
    { english_name: "Jehanabad", hindi_name: "जहानाबाद" },
    { english_name: "Ghosi", hindi_name: "घोसी" },
    { english_name: "Makhdumpur", hindi_name: "मखदुमपुर" },
    { english_name: "Goh", hindi_name: "गोह" },
    { english_name: "Obra", hindi_name: "ओबरा" },
    { english_name: "Nabinagar", hindi_name: "नबीनगर" },
    { english_name: "Kutumba", hindi_name: "कुटुम्बा" },
    { english_name: "Aurangabad", hindi_name: "औरंगाबाद" },
    { english_name: "Rafiganj", hindi_name: "रफीगंज" },
    { english_name: "Gurua", hindi_name: "गुरुआ" },
    { english_name: "Sherghati", hindi_name: "शेरघाटी" },
    { english_name: "Imamganj", hindi_name: "इमामगंज" },
    { english_name: "Barachatti", hindi_name: "बाराचट्टी" },
    { english_name: "Bodh Gaya", hindi_name: "बोधगया" },
    { english_name: "Gaya Town", hindi_name: "गया टाउन" },
    { english_name: "Tikari", hindi_name: "टिकारी" },
    { english_name: "Belaganj", hindi_name: "बेलागंज" },
    { english_name: "Atri", hindi_name: "अतरी" },
    { english_name: "Wazirganj", hindi_name: "वजीरगंज" },
    { english_name: "Rajauli", hindi_name: "रजौली" },
    { english_name: "Hisua", hindi_name: "हिसुआ" },
    { english_name: "Nawada", hindi_name: "नवादा" },
    { english_name: "Gobindpur", hindi_name: "गोविंदपुर" },
    { english_name: "Warsaliganj", hindi_name: "वारसलीगंज" },
    { english_name: "Sikandra", hindi_name: "सिकंदरा" },
    { english_name: "Jamui", hindi_name: "जमुई" },
    { english_name: "Jhajha", hindi_name: "झाझा" },
    { english_name: "Chakai", hindi_name: "चकाई" }
  ];
  
  export { constituencyNameData };